# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow_1234.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 540)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBoxP2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxP2.setGeometry(QtCore.QRect(350, 20, 241, 470))
        self.groupBoxP2.setObjectName("groupBoxP2")
        self.pushButtonDetectCorners = QtWidgets.QPushButton(self.groupBoxP2)
        self.pushButtonDetectCorners.setGeometry(QtCore.QRect(40, 30, 161, 31))
        self.pushButtonDetectCorners.setObjectName("pushButtonDetectCorners")
        self.pushButtonFindIntrinsicMatrix = QtWidgets.QPushButton(self.groupBoxP2)
        self.pushButtonFindIntrinsicMatrix.setGeometry(QtCore.QRect(40, 90, 161, 31))
        self.pushButtonFindIntrinsicMatrix.setObjectName("pushButtonFindIntrinsicMatrix")
        self.pushButtonFindDistortionMatrix = QtWidgets.QPushButton(self.groupBoxP2)
        self.pushButtonFindDistortionMatrix.setGeometry(QtCore.QRect(40, 270, 161, 31))
        self.pushButtonFindDistortionMatrix.setObjectName("pushButtonFindDistortionMatrix")
        self.pushButtonShowUndistortedResult = QtWidgets.QPushButton(self.groupBoxP2)
        self.pushButtonShowUndistortedResult.setGeometry(QtCore.QRect(40, 330, 161, 31))
        self.pushButtonShowUndistortedResult.setObjectName("pushButtonShowUndistortedResult")
        self.groupBoxP1ExtrinsicMatrix = QtWidgets.QGroupBox(self.groupBoxP2)
        self.groupBoxP1ExtrinsicMatrix.setGeometry(QtCore.QRect(40, 140, 161, 101))
        self.groupBoxP1ExtrinsicMatrix.setObjectName("groupBoxP1ExtrinsicMatrix")
        self.pushButtonFindExtrinsicMatrix = QtWidgets.QPushButton(self.groupBoxP1ExtrinsicMatrix)
        self.pushButtonFindExtrinsicMatrix.setGeometry(QtCore.QRect(10, 60, 141, 31))
        self.pushButtonFindExtrinsicMatrix.setObjectName("pushButtonFindExtrinsicMatrix")
        self.textEditExtrinsicMatrixImage = QtWidgets.QTextEdit(self.groupBoxP1ExtrinsicMatrix)
        self.textEditExtrinsicMatrixImage.setGeometry(QtCore.QRect(90, 20, 62, 31))
        self.textEditExtrinsicMatrixImage.setObjectName("textEditExtrinsicMatrixImage")
        self.labelExtrinsicMatrixPrompt = QtWidgets.QLabel(self.groupBoxP1ExtrinsicMatrix)
        self.labelExtrinsicMatrixPrompt.setGeometry(QtCore.QRect(10, 20, 81, 31))
        self.labelExtrinsicMatrixPrompt.setObjectName("labelExtrinsicMatrixPrompt")
        self.groupBoxP3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxP3.setGeometry(QtCore.QRect(610, 20, 241, 221))
        self.groupBoxP3.setObjectName("groupBoxP3")
        self.textEditWords = QtWidgets.QTextEdit(self.groupBoxP3)
        self.textEditWords.setGeometry(QtCore.QRect(40, 30, 161, 30))
        self.textEditWords.setObjectName("textEditWords")
        self.pushButtonShowWordsOnBoard = QtWidgets.QPushButton(self.groupBoxP3)
        self.pushButtonShowWordsOnBoard.setGeometry(QtCore.QRect(40, 90, 161, 31))
        self.pushButtonShowWordsOnBoard.setObjectName("pushButtonShowWordsOnBoard")
        self.pushButtonShowWordsVertically = QtWidgets.QPushButton(self.groupBoxP3)
        self.pushButtonShowWordsVertically.setGeometry(QtCore.QRect(40, 150, 161, 31))
        self.pushButtonShowWordsVertically.setObjectName("pushButtonShowWordsVertically")
        self.groupBoxP4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxP4.setGeometry(QtCore.QRect(610, 270, 241, 221))
        self.groupBoxP4.setObjectName("groupBoxP4")
        self.pushButtonShowDisparityMap = QtWidgets.QPushButton(self.groupBoxP4)
        self.pushButtonShowDisparityMap.setGeometry(QtCore.QRect(40, 30, 161, 31))
        self.pushButtonShowDisparityMap.setObjectName("pushButtonShowDisparityMap")
        self.groupBoxP1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxP1.setGeometry(QtCore.QRect(90, 20, 241, 470))
        self.groupBoxP1.setObjectName("groupBoxP1")
        self.pushButtonDrawContour = QtWidgets.QPushButton(self.groupBoxP1)
        self.pushButtonDrawContour.setGeometry(QtCore.QRect(40, 30, 161, 31))
        self.pushButtonDrawContour.setObjectName("pushButtonDrawContour")
        self.pushButtonCountRings = QtWidgets.QPushButton(self.groupBoxP1)
        self.pushButtonCountRings.setGeometry(QtCore.QRect(40, 90, 161, 31))
        self.pushButtonCountRings.setObjectName("pushButtonCountRings")
        self.labelRings1 = QtWidgets.QLabel(self.groupBoxP1)
        self.labelRings1.setGeometry(QtCore.QRect(30, 150, 181, 15))
        self.labelRings1.setObjectName("labelRings1")
        self.labelRings2 = QtWidgets.QLabel(self.groupBoxP1)
        self.labelRings2.setGeometry(QtCore.QRect(30, 190, 181, 15))
        self.labelRings2.setObjectName("labelRings2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "2021 OpenCv Homework 1"))
        self.groupBoxP2.setTitle(_translate("MainWindow", "2. Calibration"))
        self.pushButtonDetectCorners.setText(_translate("MainWindow", "2.1 Find Corners"))
        self.pushButtonFindIntrinsicMatrix.setText(_translate("MainWindow", "2.2 Find Intrinsic"))
        self.pushButtonFindDistortionMatrix.setText(_translate("MainWindow", "2.4 Find Distortion"))
        self.pushButtonShowUndistortedResult.setText(_translate("MainWindow", "2.5 Show Result"))
        self.groupBoxP1ExtrinsicMatrix.setTitle(_translate("MainWindow", "2.3 Find Extrinsic"))
        self.pushButtonFindExtrinsicMatrix.setText(_translate("MainWindow", "2.3 Find Extrinsic"))
        self.labelExtrinsicMatrixPrompt.setText(_translate("MainWindow", "Select image:"))
        self.groupBoxP3.setTitle(_translate("MainWindow", "3. Augmented Reality"))
        self.pushButtonShowWordsOnBoard.setText(_translate("MainWindow", "3.1 Show Words on Board"))
        self.pushButtonShowWordsVertically.setText(_translate("MainWindow", "3.2 Show Words Vertically"))
        self.groupBoxP4.setTitle(_translate("MainWindow", "4. Stereo Disparity Map"))
        self.pushButtonShowDisparityMap.setText(_translate("MainWindow", "4.1 Stereo Disparity Map"))
        self.groupBoxP1.setTitle(_translate("MainWindow", "1. Find Contour"))
        self.pushButtonDrawContour.setText(_translate("MainWindow", "1.1 Draw Contour"))
        self.pushButtonCountRings.setText(_translate("MainWindow", "1.2 Count Rings"))
        self.labelRings1.setText(_translate("MainWindow", "There are _ rings in img1.jpg"))
        self.labelRings2.setText(_translate("MainWindow", "There are _ rings in img2.jpg"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
